theme: jekyll-theme-architect

title: Jethva A. Minesh 
description: Ph.D. Bioinformatics, Data Science and Cancer Immuno-Genomics Researcher

# Google Analytics
google_analytics: UA-116218531-1

webrick:
  headers:
    My-Header: My-Value
    My-Other-Header: My-Other-Value

includes_dir:    _includes
collections:
  posts:
    output:   true
