theme: jekyll-theme-tactile

title: Jethva A. Minesh 
description: Data Scientist, Deep Learning Sequence Modeling for IoT Signal Processing & Computer Vision
avatar: https://avatars0.githubusercontent.com/u/6646693?s=460&v=4

# Google Analytics
google_analytics: UA-116218531-1

webrick:
  headers:
    My-Header: My-Value
    My-Other-Header: My-Other-Value

includes_dir:    _includes
collections:
  posts:
    output:   true

name: Jethva A. Minesh 
author: Jethva A. Minesh 
author_email: minesh.1291@gmail.com

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# How many articles do you wish to appear on the front page:
paginate: 3
